[package]
name = "hello_rust_lambda"
version = "0.1.0"
edition = "2021"
autobins = false

[dependencies]
lambda_runtime = "0.6.0"
serde_json = "1.0.82"
tokio = { version = "1.20.1", features = ["macros"] }

[[bin]]
name = "bootstrap"
path = "src/main.rs"
